#!/bin/bash
set -e -u

# Check current user

if [ "$(id -u)" -ne 0 ]; then
    echo 1>&2 "Impossible to execute this script without root privileges."
    exit 255
fi

# Link host folders

if [ -d /host ]; then
    ln -f -s /host/home /home
    ln -f -s /host/tmp /tmp
fi

# Run command

exec gosu "${USER:-root}" "${@:-sh}"
